### ISSUE TITLE
{{code-block}} component should not have the .codeinline class

### ISSUE THREAD

**Issue by justin-lau** [brandonjmckay/ember-prism#10]
It would be more logically correct to have `.codeinline` classes only in `{{code-inline}}` components but not in `{{code-block}}` components.

I also suggest using `.code-block` and `.code-inline` instead, which is not only more CSS-friendly, and also matches the component handlebars helper exactly.

**Comment by brandonjmckay** [comment]
Ya, I didn't catch the inheritance happening. I agree.

**Comment by brandonjmckay** [comment]
@justin-lau I'm not entirely sold on using `.code-block` instead of `.codeblock` though. Where I work we're pretty strong on smacss, so it would be more normal/conventioney to use `.modulename-attribute_name` for me.

But, I agree with you that there is goodness in matching the component name. So I'm not entirely sure where to fall on this, but I'd be ok to go with `.code-block`, and `.code-inline`.

Perhaps the convention could be `.module-name_attribute-name`? Seems imperfect, but I don't know what to do with the clash of conventions there.

**Comment by brandonjmckay** [comment]
So I'd say that it is no more CSS friendly than the current approach, yet regardless of that I think you're right in changing the convention here.

**Comment by justin-lau** [comment]
I see. I usually follow @mdo's [Code Guide](http://codeguide.co/) when it comes to convention, and [it encourages to use only dashs in class names](http://codeguide.co/#css-classes). [This StackOverflow thread](http://stackoverflow.com/questions/7560813/why-are-dashes-preferred-for-css-selectors-html-attributes) also highlighted some concerns I have about using underscores in CSS class names.

That being said, since this library is an addon to Ember and depends on Prism, and neither of them has a preference on CSS class name, I think it's totally your call to whatever convention you follow.

In fact, I'm quite surprised that Prism uses selectors like `code[class*="language-"]` which I believe may impact performance and code readability. I think this is a more serious issue then following convention alone.

**Comment by brandonjmckay** [comment]
Yes, totally. The thinking behind smacss is that you pretty much have a class for anything that you modify.

So you avoid deep nesting of `>`, or `.class .inside-aclass`. Keeps everything separate, and running fast.
After looking into it more on ember slack, I think I'll go for more of a BEM syntax, as that would work better with component names.

I just want to have an idea in mind of how to address attributes.

**Comment by brandonjmckay** [comment]
I'll do a write up on the code conventions for the repo.
I will be moving to a `.component-name` syntax like you suggest, with some BEM ideas sprinkled in.

**Comment by justin-lau** [comment]
Great :+1:
