### ISSUE TITLE
change theme after the app is loaded

### ISSUE THREAD

**Issue by SirZach** [brandonjmckay/ember-prism#12]
My site has an option to update the theme of the app and I'ld like to have the option to use one prism theme vs another (that I've defined) based on the overall theme of the app they're using.

**Comment by brandonjmckay** [comment]
So you've created your own theme?
If so, you can just use `classNames='mythemeclass'` when using the component I believe.

Or are you trying to switch between two base Prism themes?

**Comment by SirZach** [comment]
I would like to be able to switch between two different prism themes. Sorry for the oddly confused request!

**Comment by brandonjmckay** [comment]
I'll try looking into this soonish, but I've been a little busy lately. 
If you can create a PR, I'll review it, and merge it in as soon as I can.

Or if you have an idea of how to do it cleanly, I'll see if I can whip it into a PR.

**Comment by SirZach** [comment]
@brandonjmckay thanks for the replies. I'll spend some time on it this evening and comment back tomorrow on what i came up with. Initially, my thoughts are that each instantiation of the component will take a "theme" parameter. This will require you to preload all themes you care about in the Brocfile.

**Comment by SirZach** [comment]
ok, i got some code up and running to allow you to import multiple themes but I'm not sure if it's possible with prism.js to support multiple themes loaded at once. I created an issue https://github.com/PrismJS/prism/issues/643 to see what their thoughts were. If you had thoughts on doing this without needing any efforts from prism i would love to hear. thanks!

**Comment by SirZach** [comment]
I think the endgame is to have people create their own CSS files that look for specific <code>data-theme</code> attributes that this addon could supply by virtue of a <code>theme</code> parameter passed into the <code>code-block</code> and <code>code-inline</code> components. I'm not sure if you'll agree it's in the best interest of this project so I'll add it to my fork and create a PR anyways to see what you think.

**Comment by brandonjmckay** [comment]
Ok. Ya, I wasn't sure this would be possible with Prism, or not.

Looks like on their site their theme switcher swaps out which one is loaded throughout the site.
That seems like an unrealistic goal for this addon to support a theme switcher. 

You can achieve the same effect by adding different `classNames` to the component, and creating/importing themes under different class namespaces.

**Comment by brandonjmckay** [comment]
Feel free to open up a PR still, but if Prism can't do it, then I don't we'll do it in the addon.
