### ISSUE TITLE
Actively maintained?

### ISSUE THREAD

**Issue by sheriffderek** [brandonjmckay/ember-prism#16]
Hey there. Are you actively maintaining this? I'm trying to decide between jumping in and helping, or making something fresh.

> You may need to use \&lt; and \&gt; html attributes to escape <, and > characters so they aren't removed by Handlebars.

Doesn't seem like something I could live with, so that would be the first thing I investigated.

**Comment by brandonjmckay** [comment]
What do you need?

**Comment by brandonjmckay** [comment]
I'm totally welcome to PRs! It doesn't have a whole lot it needs to do other than wrap prism.
I don't use this in my own projects currently, so I'm of the mind to fix anything that comes up as a bug, but if it ain't broke...

If you have an idea on how to get past that issue, I'd be glad to review your PR and get it merged in.

**Comment by brandonjmckay** [comment]
@sheriffderek ^^

**Comment by sheriffderek** [comment]
Ok. Great. I'll see if I can keep things on this track then, unless my use-cases diverge. : )

**Comment by brandonjmckay** [comment]
@sheriffderek Actually, I just found [ember-code-snippet](https://github.com/ef4/ember-code-snippet). It looks like it addresses those formatting issues a lot better than what I did here.

**Comment by sheriffderek** [comment]
@brandonjmckay I've checked that out as well. It seems great, but it uses highlight.js - which doesn't have the plugin eco-system that prism does. Ideally, you could load prism and then also opt in (in the config) to pull in any number of additional plugins. In my case I want to use the "keep markup" plugin. http://codepen.io/sheriffderek/pen/NAYbJX

I'm trying to learn from the insides of both of these addons. This on is at 1.13 though, so it's been a learning curve trying to level it up to 2.0+ in my fork.
