### ISSUE TITLE
Needs new languages

### ISSUE THREAD

**Issue by djsegal** [brandonjmckay/ember-prism#19]
Several new languages (including `Julia`) have been added since the last update date

**Comment by JoshSmith** [comment]
Hey @brandonjmckay, just wanted to see if you wanted to bring in the latest from `npm`. We could potentially set up Greenkeeper to pull in the latest prism.

**Comment by brandonjmckay** [comment]
Sure, if someone has a PR I'll gladly pull it in. I'll check out Greenkeeper, I haven't heard of it.

**Comment by brandonjmckay** [comment]
Oh sweet! Greenkeeper sounds great.

**Comment by JoshSmith** [comment]
@brandonjmckay yeah it's a huge time saver on that so you don't need to have folks PR. Make computers do it! Helps a lot with our open source JS stuff.

**Comment by brandonjmckay** [comment]
@JoshSmith I've installed it, but I'm not sure if it's configured correctly yet.
I'll take a look by the end of the weekend(?), and try to do an update to a more recent ember-cli.

I _personally_ don't use this in any of my apps anymore... so I'm just updating things when people ask for it. I hope Greenkeeper can keep things going smoothly for everyone!

**Comment by JoshSmith** [comment]
@brandonjmckay I'm using it now and was actually considering PRing some things, so perhaps you'd be interested in transferring ownership? If it helps relieve the burden and we're actively using it, then I'd be all for it.

Is there some reason you don't use this in your apps right now, or just happen to not be working on anything that needs it?

**Comment by brandonjmckay** [comment]
@JoshSmith I'm not working on anything that needs it to be honest.
I built it when I did a PR for ember-paper, and they don't even use it anymore.

**Comment by brandonjmckay** [comment]
I can transfer you ownership, sure.

**Comment by rwwagner90** [comment]
Pulling from npm now, so this should no longer be an issue 😄
